version: '3.7'

services:
  postgres:
    environment:
      POSTGRES_USER: nest-template
      POSTGRES_PASSWORD: knfo3i4012H123af
    image: postgres:13.2-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend
    restart: always

  api:
    build: .
    volumes:
      - ./runtime:/usr/src/app/runtime
    networks:
      - backend
    ports:
      - 3000:3000
    restart: always

volumes:
  postgres:

networks:
  backend:
