version: '3.7'

services:
  postgres:
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    image: postgres:13.2-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend
    restart: unless-stopped

  api:
    image: kirinami-todos
    volumes:
      - ./runtime:/usr/src/app/runtime
    networks:
      - backend
    ports:
      - 3000:3000
    restart: unless-stopped

volumes:
  postgres:

networks:
  backend:
