version: '3.7'

services:
  postgres:
    environment:
      POSTGRES_USER: nest-template
      POSTGRES_PASSWORD: knfo3i4012H123af
    image: postgres:13.2-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

volumes:
  postgres:
