version: '3.8'

services:
  postgres:
    env_file:
      - .env.local
    image: postgres:13.2-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend
    restart: unless-stopped

  app:
    env_file:
      - .env.local
    labels:
      - traefik.enable=true
      - traefik.http.routers.kirinami_com_todos.rule=Host(`todos.kirinami.com`)
      - traefik.http.routers.kirinami_com_todos.entrypoints=web
      - traefik.http.services.kirinami_com_todos.loadbalancer.server.port=3000
    build: .
    volumes:
      - $PWD/runtime:/app/runtime
    networks:
      - traefik
      - backend
    expose:
      - 3000
    restart: unless-stopped

volumes:
  postgres:

networks:
  traefik:
    external:
      name: "traefik"
  backend:
